### ISSUE TITLE
Question : Can this work in reverse?

### ISSUE THREAD

**Issue by JoshuaCrewe** [camilstaps/HebrewParseTrainer#5]
_Sorry but this is off topic and is perhaps not the right place or channel  to ask this question. If so please ignore and close this and accept my apologies_

This application allows the learner to practice parsing a verb which is great. I was wondering if it was possible (reasonable) to have an application which does the parsing for you. The scenario is that the learner has a Hebrew word which they are a) not sure of or b) need to verify that they have understood correctly what is happening. If they could enter the word and be given a breakdown of what grammatically would be going on. The root radicals, the prefixes and suffixes etc.

The best example I can give are those websites that parse regex https://regexr.com/

I am very much a beginner at Hebrew and I don't know if this sort of parsing is too complicated/difficult for a web application to do. Given your experience with this application, are you in a position to tell me if it is really hard or theoretically possible? I feel cheeking for asking the question :blush: 

Thanks for your time reading this.

**Comment by camilstaps** [comment]
Don't worry, I'm happy to share a few thoughts (though there are others who are more knowledgeable about this stuff).

If your use case is just that you're reading a biblical text and want to look up the parsing of a form, there are many websites that you can use: http://dadel.org/ (go to Text and exercises > Display text, pick a text, and hover/click a  form to see parsing info) and https://www.blueletterbible.org/ (search for a text, click 'tools' next to a verse and click a word to see parsing info) are the ones I recommend to my students, but there are many more (https://parabible.com/ comes to mind). These websites also give info about non-verbal forms. These websites either use the [BHSA](https://etcbc.github.io/bhsa/) database or their own closed-source database, I believe.

It's more tricky if you want to do this with forms for which you have no biblical reference. In principle you could extract all verbal forms from the database above and do a lookup, but there are some issues:

1. Not all forms exist in the Hebrew Bible; especially paradigms (but also constructed exercises) can contain forms that are not attested in this corpus (with the right root).
2. In case of double forms (e.g. the 3f/2m singular imperfect, תִּקְטֹל) such a database gives you the parsing _in context_, whereas the ParseTrainer gives all possible parsings for training purposes.

(The second point is one of the reasons why the database behind the ParseTrainer is not based on the BHSA dataset: for a form like תִּקְטֹל it might then say that '3fs imperfect' is incorrect because the only instances are all 2ms, even though the parsing is correct!)

It should be possible to write an application that really automates parsing. You can't use much of the ParseTrainer logic for this though, because the ParseTrainer just has a simple database. I would be tempted to develop something like this rule-based and test-driven: start with a simple logic based on the strong verb, and use all forms in the BHSA as test cases. Every time you hit a test case that you get an incorrect parsing for, you adapt the logic. But nowadays most computational linguistic work is not rule-based anymore but something more black-box, so this approach may be outdated.

@codykingham @MartijnNaaijer may know more about more modern approaches. Cody & Martijn, if I may pull you in here, this user is interested in automatically parsing Hebrew verbs (I'm assuming out of context). I remember that at least you, Martijn, were working on a model to parse forms in-context and correct them manually, to prepare a dataset? But here it's for practicing the paradigm, so you can't have a human in the loop and it's a slightly different situation. Any idea if this has been done?

**Comment by JoshuaCrewe** [comment]
Thanks for taking the time to respond. I have been reading through in the information here and mulling over what I think I am looking for. It is quite likely that what I am thinking won't actually be any good in practice.

The Dadel link was a good one. The information they show in that modal is fairly comprehensive and does contain the sorts of information I would want to see myself. The first port of call would be to use that site and see if the extra info/presentation is a problem. I think my head is solving the presentation problem which is subjective and presumed (so that's good to recognise)

The BHSA is another interesting link, thanks for that too! 

I do think that my use case is a little faulty. I am self taught (largely) which chunks of time under some excellent tutor-age which has consistently come to abrupt ends. (usually my teacher needs to get a job!) So I spend my time in Anki doing Vocab drills for the top 680 words, Dailydose on vimeo to get some solid exposure to parsing and Aleph With Beth Videos to get some lessons in (they are hard work due to the slow pace, repetition and video format). My goal is to get proficient at reading a Readers Hebrew Bible which is coming along. This is all preamble to say that I am getting some good input but checking if I am right on things can be a little tricky. If I look it up in either a translation or online then I risk taking in more information that I want to. I will learn the troubling part but also reveal the next sentence as well.

I imagined being able to input the specific form I needed to check in on its own and get just that word broken down (like the regex explainer) without revealing anything else. Context is not something I had considered at all (something I am avoiding) but is a really valid point and I am grateful that you pointed it out.

I had forgotten about this as well :
https://piped.kavin.rocks/watch?v=GTa-zMSS57g
(My last teacher funnily enough)

Which shows that it is possible. I really didn't like Logos very much. The definition of proprietary, they really want to keep you locked in to their ecosystem. The LHB is another 40 quid for something I essentially already own in print four times. grumble grumble.

I am still keen to work on something in the future I think but I would need to know it would be useful and not just an exercise in avoiding the traditional grind of learning Vocab and practicing parsing. Thanks so much for the input and the links!

**Comment by JoshuaCrewe** [comment]
Parabible is a very nice implementation (and open source) which looks like it will work nicely.

**Comment by camilstaps** [comment]
@JoshuaCrewe glad to be of help!

Since you mention you're mostly self-taught: I'm running a small online reading group for people who want to improve/maintain their Hebrew but don't have time or resources for a full course, or can't find a suitable course. If you're interested you can always join one of our meetings and see if it can be useful to you right now. Originally the idea was to target people who have done all derived stems and have seen some weak verb classes, but it's flexible, and by choosing whether or not you prepare the reading you can also adjust difficulty to the right level. Some of us don't prepare but use dadel or parabible, etc., and together we manage to answer most questions we come up with. We are currently meeting Tuesdays at 20:00 Amsterdam time. If you're interested you can always send me an email and I can send the zoom link; if not, that's fine too!

(That invitation extends to anyone else reading this later as well, of course!)

**Comment by JoshuaCrewe** [comment]
@camilstaps ah that reading group sound excellent! Right now I have my schedule worked out and have a working plan. In the future I absolutely want to join a reading group. I am not there yet. My grammar needs some work now that my vocab has plateued.

I would love to reconnect further down the line though if that's still cool.

Feeling pumped right now as I translated 1 Samuel 1:4 ✊with just the Hebrew and a pen.

**Comment by camilstaps** [comment]
Of course! Just let me know whenever you feel like joining :)
